" Name:         BRB
" Author:       Gianmaria Bajo (mg1979@git.gmail.com)
" Maintainer:   Gianmaria Bajo (mg1979@git.gmail.com)
" License:      Vim License (see `:help license`)
" Last Updated: gio 30 set 2021 09:41:55 CEST

" Generated by Colortemplate v2.1.0

hi clear
let g:colors_name = 'brg'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if exists('g:loaded_visual_multi')
    let g:VM_theme_set_by_colorscheme = 1
    if &background == 'light'
      hi VM_extend ctermbg=158    ctermfg=237    guibg=#AAF0D6    guifg=NONE
      hi VM_cursor ctermbg=80     ctermfg=235    guibg=#78dede    guifg=#262626
      hi VM_insert ctermbg=229    ctermfg=235    guibg=#ffffaf    guifg=#262626
      hi VM_mono   ctermbg=124    ctermfg=231    guibg=#B23A2D    guifg=#ffffff
    else
      hi VM_extend ctermbg=66     ctermfg=231    guibg=#5f8787    guifg=#ffffff
      hi VM_cursor ctermbg=36     ctermfg=231    guibg=#00af87    guifg=#ffffff
      hi VM_insert ctermbg=54     ctermfg=231    guibg=#5f0087    guifg=#ffffff
      hi VM_mono   ctermbg=167    ctermfg=231    guibg=#e05f51    guifg=#ffffff
    endif
  endif
  hi! link Character Constant
  hi! link Number Constant
  hi! link Boolean Constant
  hi! link Float Constant
  hi! link Operator Identifier
  hi! link Conditional Statement
  hi! link Repeat Statement
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Exception Statement
  hi! link Include PreProc
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link SpecialChar Special
  hi! link SpecialKey Special
  hi! link Tag Special
  hi! link Delimiter Special
  hi! link SpecialComment Special
  hi! link Debug Special
  hi! link Ignore Special
  hi! link WarningMsg Error
  hi! link Directory Constant
  hi! link Todo Visual
  hi! link Search PmenuSel
  hi! link IncSearch StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link TabLine StatusLineNC
  hi! link LineNr NonText
  hi! link FoldColumn SignColumn
  hi! link MatchParen Error
  hi! link VertSplit TabLineFill
  hi! link WildMenu Visual
  hi! link diffAdded Statement
  hi! link diffRemoved WarningMsg
  hi! link DiffLine StatusLineNC
  hi! link cSpecial Type
  hi! link cBraces Delimiter
  hi! link csBraces Delimiter
  hi! link helpHyperTextEntry Type
  hi! link helpHyperTextJump Constant
  hi! link helpOption Constant
  hi! link helpCommand Statement
  hi! link helpExample Statement
  hi! link helpSectionDelim Constant
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#262626', '#e05f51', '#57875f', '#fa9153', '#5b7fbd', '#ff81ca', '#5787af', '#bcbcbc', '#bcbcbc', '#ff5e56', '#70b433', '#efc541', '#5b7fbd', '#ff81ca', '#88a1c1', '#eeeeee']
    if has('nvim')
      let g:terminal_color_0 = '#262626'
      let g:terminal_color_1 = '#e05f51'
      let g:terminal_color_2 = '#57875f'
      let g:terminal_color_3 = '#fa9153'
      let g:terminal_color_4 = '#5b7fbd'
      let g:terminal_color_5 = '#ff81ca'
      let g:terminal_color_6 = '#5787af'
      let g:terminal_color_7 = '#bcbcbc'
      let g:terminal_color_8 = '#bcbcbc'
      let g:terminal_color_9 = '#ff5e56'
      let g:terminal_color_10 = '#70b433'
      let g:terminal_color_11 = '#efc541'
      let g:terminal_color_12 = '#5b7fbd'
      let g:terminal_color_13 = '#ff81ca'
      let g:terminal_color_14 = '#88a1c1'
      let g:terminal_color_15 = '#eeeeee'
    endif
    hi Normal guifg=#bcbcbc guibg=#262626 gui=NONE cterm=NONE
    hi Comment guifg=#666666 guibg=NONE gui=NONE cterm=NONE
    hi String guifg=#57875f guibg=NONE gui=NONE cterm=NONE
    hi Constant guifg=#57875f guibg=NONE gui=NONE cterm=NONE
    hi Number guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Operator guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi Function guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    hi Identifier guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi Statement guifg=#88a1c1 guibg=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#5787af guibg=NONE gui=NONE cterm=NONE
    hi Type guifg=#88a1c1 guibg=NONE gui=NONE cterm=NONE
    hi Title guifg=#eeeeee guibg=NONE gui=bold cterm=bold
    hi Special guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi NonText guifg=#585858 guibg=NONE gui=NONE cterm=NONE
    hi Underlined guifg=fg guibg=NONE gui=underline cterm=underline
    hi Error guifg=#ff5e56 guibg=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#ff5e56 guibg=NONE gui=reverse cterm=reverse
    hi Visual guifg=NONE guibg=#444444 gui=NONE cterm=NONE
    hi Terminal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi StatusLine guifg=#3b3b3b guibg=#777777 gui=NONE cterm=NONE
    hi StatusLineNC guifg=#777777 guibg=#3b3b3b gui=NONE cterm=NONE
    hi Pmenu guifg=#777777 guibg=#222222 gui=NONE cterm=NONE
    hi PmenuSbar guifg=#3b3b3b guibg=#3b3b3b gui=NONE cterm=NONE
    hi PmenuSel guifg=#eeeeee guibg=#3b3b3b gui=bold cterm=bold
    hi PmenuThumb guifg=#777777 guibg=#777777 gui=NONE cterm=NONE
    hi TabLineFill guifg=#3b3b3b guibg=#3b3b3b gui=NONE cterm=NONE
    hi ToolbarLine guifg=NONE guibg=#1e1e1e gui=NONE cterm=NONE
    hi ToolbarButton guifg=#777777 guibg=#3b3b3b gui=NONE cterm=NONE
    hi Cursor guifg=#eeeeee guibg=#5787af gui=NONE cterm=NONE
    hi CursorColumn guifg=NONE guibg=#303030 gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#303030 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#777777 guibg=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#3b3b3b guibg=NONE gui=NONE cterm=NONE
    hi Folded guifg=#666666 guibg=#1e1e1e gui=NONE cterm=NONE
    hi SignColumn guifg=#666666 guibg=#1e1e1e gui=NONE cterm=NONE
    hi QuickFixLine guifg=NONE guibg=#1e1e1e gui=NONE cterm=NONE
    hi ModeMsg guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#70b433 guibg=NONE gui=NONE cterm=NONE
    hi Question guifg=#efc541 guibg=NONE gui=NONE cterm=NONE
    hi Search guifg=#70b433 guibg=NONE gui=bold,reverse cterm=bold,reverse
    hi IncSearch guifg=#efc541 guibg=NONE gui=bold,reverse cterm=bold,reverse
    hi DiffAdd guifg=#5b7fbd guibg=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#57875f guibg=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#e05f51 guibg=NONE gui=bold cterm=bold
    hi DiffText guifg=#e05f51 guibg=NONE gui=bold,reverse cterm=bold,reverse
    hi diffAdded guifg=#57875f guibg=NONE gui=NONE cterm=NONE
    hi diffChanged guifg=#fa9153 guibg=NONE gui=NONE cterm=NONE
    hi diffRemoved guifg=#e05f51 guibg=NONE gui=NONE cterm=NONE
    hi GitGutterAdd guifg=#70b433 guibg=#1e1e1e gui=NONE cterm=NONE
    hi GitGutterChange guifg=#fa9153 guibg=#1e1e1e gui=NONE cterm=NONE
    hi GitGutterDelete guifg=#ff5e56 guibg=#1e1e1e gui=bold cterm=bold
    let $BAT_THEME = 'zenburn'
    if exists('g:loaded_xtabline')
      if !exists('s:xt_dark')
        let s:xt_dark = 1
        call xtabline#hi#generate('brg_dark', {
              \"XTSelect":      [ 235, 36,  '#262626',   '#777777',   0 ],
              \"XTSelectMod":   [ 196, 36,  '#ff5e56',   '#777777',   0 ],
              \"XTVisible":     [ 240, 235, '#585858',   'bg',        0 ],
              \"XTVisibleMod":  [ 196, 235, '#ff5e56',   'bg',        0 ],
              \"XTHidden":      [ 36,  237, '#777777',   '#3a3a3a',   0 ],
              \"XTHiddenMod":   [ 196, 237, '#ff5e56',   '#3a3a3a',   0 ],
              \"XTExtra":       [ 250, 237, '#bcbcbc',   '#3a3a3a',   0 ],
              \"XTExtraMod":    [ 196, 237, '#ff5e56',   '#3a3a3a',   0 ],
              \"XTSpecial":     [ 250, 54,  'fg',        '#5f0087',   0 ],
              \"XTNumSel":      [ 167, 150, '#e05f51',   'NONE',      1 ],
              \"XTNum":         [ 68,  233, '#5b7fbd',   'NONE',      0 ],
              \"XTCorner":      [ 229, 237, '#efc541',   '#3a3a3a',   0 ],
              \"XTFill":        [ 68,  0,   '#5b7fbd',   'NONE',      0 ],
              \})
      endif
      XTabTheme brg_dark
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#000000', '#b23a2d', '#006000', '#ff8700', '#073655', '#5f0087', '#4a679a', '#c9c9c9', '#c9c9c9', '#ff0000', '#57875f', '#ffffaf', '#4a679a', '#ff87ff', '#4a679a', '#e2e9f1']
  if has('nvim')
    let g:terminal_color_0 = '#000000'
    let g:terminal_color_1 = '#b23a2d'
    let g:terminal_color_2 = '#006000'
    let g:terminal_color_3 = '#ff8700'
    let g:terminal_color_4 = '#073655'
    let g:terminal_color_5 = '#5f0087'
    let g:terminal_color_6 = '#4a679a'
    let g:terminal_color_7 = '#c9c9c9'
    let g:terminal_color_8 = '#c9c9c9'
    let g:terminal_color_9 = '#ff0000'
    let g:terminal_color_10 = '#57875f'
    let g:terminal_color_11 = '#ffffaf'
    let g:terminal_color_12 = '#4a679a'
    let g:terminal_color_13 = '#ff87ff'
    let g:terminal_color_14 = '#4a679a'
    let g:terminal_color_15 = '#e2e9f1'
  endif
  hi Normal guifg=#000000 guibg=#f5f5f5 gui=NONE cterm=NONE
  hi Comment guifg=#a9a9a9 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#b23a2d guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#006000 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#262626 guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#4a679a guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#4a679a guibg=NONE gui=bold cterm=bold
  hi Type guifg=#4a679a guibg=NONE gui=bold cterm=bold
  hi Title guifg=fg guibg=NONE gui=bold cterm=bold
  hi Special guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#a9a9a9 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=fg guibg=NONE gui=underline cterm=underline
  hi Error guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#f5f5f5 guibg=#ff0000 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi Terminal guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi StatusLine guifg=#f5f5f5 guibg=#4a679a gui=NONE cterm=NONE
  hi StatusLineNC guifg=#6c6c6c guibg=#c9c9c9 gui=NONE cterm=NONE
  hi Pmenu guifg=#262626 guibg=#e2e9f1 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#a9a9a9 gui=NONE cterm=NONE
  hi PmenuSel guifg=#f5f5f5 guibg=#4a679a gui=NONE cterm=NONE
  hi PmenuThumb guifg=#073655 guibg=#073655 gui=NONE cterm=NONE
  hi TabLineFill guifg=#e2e9f1 guibg=#e2e9f1 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#c9c9c9 guibg=#4a679a gui=NONE cterm=NONE
  hi Cursor guifg=#f5f5f5 guibg=#073655 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#f5f5f5 guibg=#a9a9a9 gui=NONE cterm=NONE
  hi Folded guifg=#6c6c6c guibg=#eaeaea gui=italic cterm=italic
  hi SignColumn guifg=#6c6c6c guibg=#eaeaea gui=NONE cterm=NONE
  hi QuickFixLine guifg=fg guibg=#eaeaea gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#aaf0d6 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#e2e9f1 gui=NONE cterm=NONE
  hi DiffDelete guifg=#ff0000 guibg=NONE gui=bold cterm=bold
  hi DiffText guifg=NONE guibg=#ffffaf gui=bold cterm=bold
  hi diffAdded guifg=#006000 guibg=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#ff8700 guibg=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#730b00 guibg=NONE gui=NONE cterm=NONE
  hi GitGutterAdd guifg=#006000 guibg=#eaeaea gui=NONE cterm=NONE
  hi GitGutterChange guifg=#ff8700 guibg=#eaeaea gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ff0000 guibg=#eaeaea gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
  endif
  let $BAT_THEME = 'GitHub'
  if exists('g:loaded_xtabline')
    if !exists('s:theme_light')
      let s:theme_light = 1
      call xtabline#hi#generate('minimal_light', {
            \"XTSelect":      [ 255, 60,  '#f5f5f5',   '#4a679a',   0 ],
            \"XTSelectMod":   [ 196, 60,  '#ff0000',   '#4a679a',   0 ],
            \"XTVisible":     [ 240, 255, '#585858',   'bg',        0 ],
            \"XTVisibleMod":  [ 196, 255, '#ff0000',   'bg',        0 ],
            \"XTHidden":      [ 60,  255, '#4a679a',   '#eaeaea',   0 ],
            \"XTHiddenMod":   [ 196, 255, '#ff0000',   '#eaeaea',   0 ],
            \"XTExtra":       [ 29,  255, '#338768',   '#eaeaea',   0 ],
            \"XTExtraMod":    [ 196, 255, '#ff0000',   '#eaeaea',   0 ],
            \"XTSpecial":     [ 255, 54,  'bg',        '#5f0087',   0 ],
            \"XTNumSel":      [ 124, 251, '#B23A2D',   '#c9c9c9',   1 ],
            \"XTNum":         [ 60,  251, '#4a679a',   '#c9c9c9',   0 ],
            \"XTCorner":      [ 229, 60,  '#ffffaf',   '#4a679a',   0 ],
            \"XTFill":        [ 60,  0,   '#4a679a',   'NONE',      0 ],
            \})
    endif
    XTabTheme minimal_light
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if exists('g:loaded_visual_multi')
    let g:VM_theme_set_by_colorscheme = 1
    if &background == 'light'
      hi VM_extend ctermbg=158    ctermfg=237    guibg=#AAF0D6    guifg=NONE
      hi VM_cursor ctermbg=80     ctermfg=235    guibg=#78dede    guifg=#262626
      hi VM_insert ctermbg=229    ctermfg=235    guibg=#ffffaf    guifg=#262626
      hi VM_mono   ctermbg=124    ctermfg=231    guibg=#B23A2D    guifg=#ffffff
    else
      hi VM_extend ctermbg=66     ctermfg=231    guibg=#5f8787    guifg=#ffffff
      hi VM_cursor ctermbg=36     ctermfg=231    guibg=#00af87    guifg=#ffffff
      hi VM_insert ctermbg=54     ctermfg=231    guibg=#5f0087    guifg=#ffffff
      hi VM_mono   ctermbg=167    ctermfg=231    guibg=#e05f51    guifg=#ffffff
    endif
  endif
  hi! link Character Constant
  hi! link Number Constant
  hi! link Boolean Constant
  hi! link Float Constant
  hi! link Operator Identifier
  hi! link Conditional Statement
  hi! link Repeat Statement
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Exception Statement
  hi! link Include PreProc
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link SpecialChar Special
  hi! link SpecialKey Special
  hi! link Tag Special
  hi! link Delimiter Special
  hi! link SpecialComment Special
  hi! link Debug Special
  hi! link Ignore Special
  hi! link WarningMsg Error
  hi! link Directory Constant
  hi! link Todo Visual
  hi! link Search PmenuSel
  hi! link IncSearch StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link TabLine StatusLineNC
  hi! link LineNr NonText
  hi! link FoldColumn SignColumn
  hi! link MatchParen Error
  hi! link VertSplit TabLineFill
  hi! link WildMenu Visual
  hi! link diffAdded Statement
  hi! link diffRemoved WarningMsg
  hi! link DiffLine StatusLineNC
  hi! link cSpecial Type
  hi! link cBraces Delimiter
  hi! link csBraces Delimiter
  hi! link helpHyperTextEntry Type
  hi! link helpHyperTextJump Constant
  hi! link helpOption Constant
  hi! link helpCommand Statement
  hi! link helpExample Statement
  hi! link helpSectionDelim Constant
  if &background ==# 'dark'
    hi Normal ctermfg=250 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Comment ctermfg=241 ctermbg=NONE cterm=NONE
    hi String ctermfg=65 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=65 ctermbg=NONE cterm=NONE
    hi Number ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Operator ctermfg=246 ctermbg=NONE cterm=NONE
    hi Function ctermfg=255 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=fg ctermbg=NONE cterm=NONE
    hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=67 ctermbg=NONE cterm=NONE
    hi Type ctermfg=110 ctermbg=NONE cterm=NONE
    hi Title ctermfg=255 ctermbg=NONE cterm=bold
    hi Special ctermfg=246 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=240 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=fg ctermbg=NONE cterm=underline
    hi Error ctermfg=203 ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=reverse
    hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
    hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=237 ctermbg=243 cterm=NONE
    hi StatusLineNC ctermfg=243 ctermbg=237 cterm=NONE
    hi Pmenu ctermfg=243 ctermbg=235 cterm=NONE
    hi PmenuSbar ctermfg=237 ctermbg=237 cterm=NONE
    hi PmenuSel ctermfg=255 ctermbg=237 cterm=bold
    hi PmenuThumb ctermfg=243 ctermbg=243 cterm=NONE
    hi TabLineFill ctermfg=237 ctermbg=237 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
    hi ToolbarButton ctermfg=243 ctermbg=237 cterm=NONE
    hi Cursor ctermfg=255 ctermbg=67 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=237 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=241 ctermbg=234 cterm=NONE
    hi SignColumn ctermfg=241 ctermbg=234 cterm=NONE
    hi QuickFixLine ctermfg=NONE ctermbg=234 cterm=NONE
    hi ModeMsg ctermfg=255 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=70 ctermbg=NONE cterm=NONE
    hi Question ctermfg=221 ctermbg=NONE cterm=NONE
    hi Search ctermfg=70 ctermbg=NONE cterm=bold,reverse
    hi IncSearch ctermfg=221 ctermbg=NONE cterm=bold,reverse
    hi DiffAdd ctermfg=68 ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=65 ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=167 ctermbg=NONE cterm=bold
    hi DiffText ctermfg=167 ctermbg=NONE cterm=bold,reverse
    hi diffAdded ctermfg=65 ctermbg=NONE cterm=NONE
    hi diffChanged ctermfg=209 ctermbg=NONE cterm=NONE
    hi diffRemoved ctermfg=167 ctermbg=NONE cterm=NONE
    hi GitGutterAdd ctermfg=70 ctermbg=234 cterm=NONE
    hi GitGutterChange ctermfg=209 ctermbg=234 cterm=NONE
    hi GitGutterDelete ctermfg=203 ctermbg=234 cterm=bold
    let $BAT_THEME = 'zenburn'
    if exists('g:loaded_xtabline')
      if !exists('s:xt_dark')
        let s:xt_dark = 1
        call xtabline#hi#generate('brg_dark', {
              \"XTSelect":      [ 235, 36,  '#262626',   '#777777',   0 ],
              \"XTSelectMod":   [ 196, 36,  '#ff5e56',   '#777777',   0 ],
              \"XTVisible":     [ 240, 235, '#585858',   'bg',        0 ],
              \"XTVisibleMod":  [ 196, 235, '#ff5e56',   'bg',        0 ],
              \"XTHidden":      [ 36,  237, '#777777',   '#3a3a3a',   0 ],
              \"XTHiddenMod":   [ 196, 237, '#ff5e56',   '#3a3a3a',   0 ],
              \"XTExtra":       [ 250, 237, '#bcbcbc',   '#3a3a3a',   0 ],
              \"XTExtraMod":    [ 196, 237, '#ff5e56',   '#3a3a3a',   0 ],
              \"XTSpecial":     [ 250, 54,  'fg',        '#5f0087',   0 ],
              \"XTNumSel":      [ 167, 150, '#e05f51',   'NONE',      1 ],
              \"XTNum":         [ 68,  233, '#5b7fbd',   'NONE',      0 ],
              \"XTCorner":      [ 229, 237, '#efc541',   '#3a3a3a',   0 ],
              \"XTFill":        [ 68,  0,   '#5b7fbd',   'NONE',      0 ],
              \})
      endif
      XTabTheme brg_dark
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Normal ctermfg=16 ctermbg=255 cterm=NONE
  hi Comment ctermfg=248 ctermbg=NONE cterm=NONE
  hi String ctermfg=124 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=22 ctermbg=NONE cterm=NONE
  hi Function ctermfg=235 ctermbg=NONE cterm=bold
  hi Identifier ctermfg=fg ctermbg=NONE cterm=NONE
  hi Statement ctermfg=60 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=60 ctermbg=NONE cterm=bold
  hi Type ctermfg=60 ctermbg=NONE cterm=bold
  hi Title ctermfg=fg ctermbg=NONE cterm=bold
  hi Special ctermfg=242 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=248 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=fg ctermbg=NONE cterm=underline
  hi Error ctermfg=196 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=255 ctermbg=196 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi Terminal ctermfg=NONE ctermbg=254 cterm=NONE
  hi StatusLine ctermfg=255 ctermbg=60 cterm=NONE
  hi StatusLineNC ctermfg=242 ctermbg=251 cterm=NONE
  hi Pmenu ctermfg=235 ctermbg=254 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=248 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=60 cterm=NONE
  hi PmenuThumb ctermfg=24 ctermbg=24 cterm=NONE
  hi TabLineFill ctermfg=254 ctermbg=254 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=254 cterm=NONE
  hi ToolbarButton ctermfg=251 ctermbg=60 cterm=NONE
  hi Cursor ctermfg=255 ctermbg=24 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=254 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=254 cterm=NONE
  hi CursorLineNr ctermfg=255 ctermbg=248 cterm=NONE
  hi Folded ctermfg=242 ctermbg=254 cterm=italic
  hi SignColumn ctermfg=242 ctermbg=254 cterm=NONE
  hi QuickFixLine ctermfg=fg ctermbg=254 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=158 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=254 cterm=NONE
  hi DiffDelete ctermfg=196 ctermbg=NONE cterm=bold
  hi DiffText ctermfg=NONE ctermbg=229 cterm=bold
  hi diffAdded ctermfg=22 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=208 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=88 ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=22 ctermbg=254 cterm=NONE
  hi GitGutterChange ctermfg=208 ctermbg=254 cterm=NONE
  hi GitGutterDelete ctermfg=196 ctermbg=254 cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
  endif
  let $BAT_THEME = 'GitHub'
  if exists('g:loaded_xtabline')
    if !exists('s:theme_light')
      let s:theme_light = 1
      call xtabline#hi#generate('minimal_light', {
            \"XTSelect":      [ 255, 60,  '#f5f5f5',   '#4a679a',   0 ],
            \"XTSelectMod":   [ 196, 60,  '#ff0000',   '#4a679a',   0 ],
            \"XTVisible":     [ 240, 255, '#585858',   'bg',        0 ],
            \"XTVisibleMod":  [ 196, 255, '#ff0000',   'bg',        0 ],
            \"XTHidden":      [ 60,  255, '#4a679a',   '#eaeaea',   0 ],
            \"XTHiddenMod":   [ 196, 255, '#ff0000',   '#eaeaea',   0 ],
            \"XTExtra":       [ 29,  255, '#338768',   '#eaeaea',   0 ],
            \"XTExtraMod":    [ 196, 255, '#ff0000',   '#eaeaea',   0 ],
            \"XTSpecial":     [ 255, 54,  'bg',        '#5f0087',   0 ],
            \"XTNumSel":      [ 124, 251, '#B23A2D',   '#c9c9c9',   1 ],
            \"XTNum":         [ 60,  251, '#4a679a',   '#c9c9c9',   0 ],
            \"XTCorner":      [ 229, 60,  '#ffffaf',   '#4a679a',   0 ],
            \"XTFill":        [ 60,  0,   '#4a679a',   'NONE',      0 ],
            \})
    endif
    XTabTheme minimal_light
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: any
" Background: dark
" Color:	md_dark		#262626	~
" Color:	md_darkred	#e05f51 ~
" Color:	md_darkgreen	#57875f	~
" Color:	md_darkyellow	#fa9153	~
" Color:	md_darkblue	#073655	~
" Color:	md_darkmagenta	#5f0087	~
" Color:	md_darkcyan	#5787af ~
" Color:	md_lightgrey	#bcbcbc	~
" Color:	md_darkgrey	#585858	~
" Color:	md_red		#ff5e56	~
" Color:	md_green	#70B433	~
" Color:	md_yellow	#efc541	~
" Color:	md_blue		#5b7fbd	~
" Color:	md_magenta	#ff81ca	~
" Color:	md_cyan		#88a1c1	~
" Color:	md_white	#eeeeee	~
" Color:	md_black	#1e1e1e ~
" Color:	md_pmenu	#222222 ~
" Color:	md_grey		#949494 ~
" Color:	md_comment	#666666 ~
" Color:	md_uilight	#777777 ~
" Color:	md_uidark	#3b3b3b ~
" Color:	md_cline	#303030 ~
" Color:	md_visual	#444444 ~
" Color:	md_delete	#730b00 ~
" Term Colors: md_dark		md_darkred	md_darkgreen	md_darkyellow
" Term Colors: md_blue		md_magenta	md_darkcyan	md_lightgrey
" Term Colors: md_lightgrey	md_red		md_green	md_yellow
" Term Colors: md_blue		md_magenta	md_cyan		md_white
" Background: light
" Color:	ml_black	#000000	~
" Color:	ml_darkred	#B23A2D ~
" Color:	ml_darkgreen	#006000	~
" Color:	ml_darkyellow	#ff8700	~
" Color:	ml_darkblue	#073655	~
" Color:	ml_darkmagenta	#5f0087	~
" Color:	ml_darkcyan	#00afdf ~
" Color:	ml_lightgrey	#c9c9c9	~
" Color:	ml_darkgrey	#a9a9a9	~
" Color:	ml_red		#ff0000	~
" Color:	ml_green	#57875f	~
" Color:	ml_yellow	#ffffaf	~
" Color:	ml_blue		#4a679a	~
" Color:	ml_magenta	#ff87ff	~
" Color:	ml_cyan		#78dede	~
" Color:	ml_white	#f5f5f5	~
" Color:	ml_dark		#262626 ~
" Color:	ml_grey		#6c6c6c	~
" Color:	ml_visual	#e2e9f1 ~
" Color:	ml_signcol	#eaeaea 254 White
" Color:	ml_add		#AAF0D6 ~
" Color:	ml_delete	#730b00 ~
" Term Colors: ml_black		ml_darkred	ml_darkgreen	ml_darkyellow
" Term Colors: ml_darkblue	ml_darkmagenta	ml_blue		ml_lightgrey
" Term Colors: ml_lightgrey	ml_red		ml_green	ml_yellow
" Term Colors: ml_blue		ml_magenta	ml_blue		ml_visual
" vim: et ts=2 sw=2
